/**
 * Per-case forensic PDF report (pdf-lib, serverless-safe — no font files on disk).
 * Contains everything the analysis produced, laid out for a non-expert reader:
 * verdict, plain-English summary, message details, scored evidence with
 * rationale, authentication results, the relay trace + trust boundary, extracted
 * IOCs, and analyzer coverage.
 */

import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from 'pdf-lib';
import type { CaseRecord } from './case-service';
import { caseArtifacts } from './case-service';

const A4 = { w: 595.28, h: 841.89 };
const MARGIN = 48;
const CONTENT_W = A4.w - MARGIN * 2;

const INK = rgb(0.106, 0.145, 0.349);
const MUTED = rgb(0.44, 0.49, 0.68);
const VIOLET = rgb(0.263, 0.094, 1);
const LINE = rgb(0.88, 0.9, 0.96);
const CRIT = rgb(0.93, 0.36, 0.31);
const HIGH = rgb(1.0, 0.63, 0.26);
const LOW = rgb(0.004, 0.71, 0.45);
const MED = rgb(0.72, 0.53, 0);

function bandColor(band: string) {
  return band === 'CRITICAL' ? CRIT : band === 'HIGH_RISK' ? HIGH : band === 'SUSPICIOUS' ? MED : LOW;
}

const TYPE: Record<string, [string, string]> = {
  payment_diversion_intent: ['BEC', 'Payment diversion'], executive_impersonation: ['Impersonation', 'Authority abuse'],
  credential_harvest_intent: ['Phishing', 'Credential theft'], classifier_phishing_high: ['Phishing', 'Credential theft'],
  brand_lookalike_domain: ['Impersonation', 'Brand abuse'], fake_reply: ['BEC', 'Fake reply thread'],
  hidden_text_mismatch: ['Content injection', 'AI-assistant manipulation'], forged_received_hop: ['Spoofing', 'Sender forgery'],
  private_ip_in_public_chain: ['Spoofing', 'Header forgery'], spf_fail_hard: ['Spoofing', 'Auth failure'],
  dmarc_fail_strict: ['Spoofing', 'Policy violation'], origin_anonymized: ['Evasion', 'Origin concealment'],
  campaign_infrastructure_reuse: ['Campaign', 'Coordinated attack'], reply_to_domain_mismatch: ['BEC', 'Reply diversion'],
};

export async function buildReportPdf(rec: CaseRecord): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const mono = await doc.embedFont(StandardFonts.Courier);

  let page: PDFPage = doc.addPage([A4.w, A4.h]);
  let y = A4.h - MARGIN;
  let pageNo = 1;

  const footer = () => {
    page.drawText('Generated by Mailtrace — Email Threat Intelligence', { x: MARGIN, y: 26, size: 7, font, color: MUTED });
    page.drawText(`Case ${rec.case_id.slice(0, 8)} · page ${pageNo}`, { x: A4.w - MARGIN - 150, y: 26, size: 7, font, color: MUTED });
  };
  const newPage = () => { footer(); page = doc.addPage([A4.w, A4.h]); y = A4.h - MARGIN; pageNo += 1; };
  const need = (h: number) => { if (y - h < MARGIN + 24) newPage(); };

  const wrap = (s: string, size: number, f: PDFFont, maxW: number): string[] => {
    const out: string[] = [];
    for (const raw of (s || '').split('\n')) {
      let line = '';
      for (const word of raw.split(/\s+/)) {
        const t = line ? `${line} ${word}` : word;
        if (f.widthOfTextAtSize(t, size) > maxW && line) { out.push(line); line = word; } else line = t;
      }
      out.push(line);
    }
    return out;
  };

  const text = (s: string, o: { size?: number; f?: PDFFont; color?: ReturnType<typeof rgb>; x?: number; gap?: number } = {}) => {
    const { size = 9.5, f = font, color = INK, x = MARGIN, gap = 4 } = o;
    for (const ln of wrap(s, size, f, CONTENT_W - (x - MARGIN))) {
      need(size + gap);
      page.drawText(ln, { x, y: y - size, size, font: f, color });
      y -= size + gap;
    }
  };

  const heading = (s: string) => {
    need(30); y -= 12;
    page.drawText(s, { x: MARGIN, y: y - 12, size: 12.5, font: bold, color: VIOLET });
    y -= 16;
    page.drawLine({ start: { x: MARGIN, y }, end: { x: A4.w - MARGIN, y }, thickness: 1, color: LINE });
    y -= 8;
  };

  const kv = (k: string, v: string, f: PDFFont = font) => {
    need(14);
    page.drawText(k, { x: MARGIN, y: y - 9, size: 9, font, color: MUTED });
    for (const ln of wrap(v || '—', 9.5, f, CONTENT_W - 130)) {
      page.drawText(ln, { x: MARGIN + 130, y: y - 9, size: 9.5, font: f, color: INK });
      y -= 13;
    }
    y -= 1;
  };

  // ---- header band ----
  page.drawRectangle({ x: 0, y: A4.h - 84, width: A4.w, height: 84, color: rgb(0.957, 0.933, 1) });
  page.drawText('MAILTRACE', { x: MARGIN, y: A4.h - 40, size: 20, font: bold, color: VIOLET });
  page.drawText('Email Threat — Forensic Analysis Report', { x: MARGIN, y: A4.h - 58, size: 11, font, color: INK });
  page.drawText(`Generated ${new Date().toISOString().replace('T', ' ').slice(0, 16)} UTC`, { x: MARGIN, y: A4.h - 72, size: 8, font, color: MUTED });
  y = A4.h - 104;

  const v = rec.verdict;

  // ---- verdict box ----
  need(78);
  page.drawRectangle({ x: MARGIN, y: y - 66, width: CONTENT_W, height: 66, borderColor: LINE, borderWidth: 1, color: rgb(0.98, 0.98, 1) });
  page.drawText(`${v.score}`, { x: MARGIN + 16, y: y - 46, size: 34, font: bold, color: bandColor(v.band) });
  page.drawText('/100', { x: MARGIN + 16 + bold.widthOfTextAtSize(`${v.score}`, 34) + 4, y: y - 42, size: 11, font, color: MUTED });
  page.drawText(v.band.replace('_', ' '), { x: MARGIN + 16, y: y - 58, size: 10, font: bold, color: bandColor(v.band) });
  const pos = v.contributions.filter((c) => c.points > 0).sort((a, b) => b.points - a.points);
  const [cat, intent] = (pos[0] && TYPE[pos[0].signal]) || (pos.length ? ['Suspicious', 'Undetermined'] : ['Clean', 'None detected']);
  const bx = MARGIN + 150;
  page.drawText('CLASSIFICATION', { x: bx, y: y - 16, size: 7.5, font: bold, color: MUTED });
  page.drawText(cat, { x: bx, y: y - 30, size: 12, font: bold, color: INK });
  page.drawText(`Attack intent: ${intent}`, { x: bx, y: y - 44, size: 9, font, color: MUTED });
  const cx = MARGIN + 360;
  page.drawText('CONFIDENCE', { x: cx, y: y - 16, size: 7.5, font: bold, color: MUTED });
  page.drawText(`${Math.round(v.confidence * 100)}%`, { x: cx, y: y - 32, size: 14, font: bold, color: INK });
  page.drawText(`Scorer v${v.scorer_version}`, { x: cx, y: y - 46, size: 8, font, color: MUTED });
  y -= 78;

  text(v.summary, { size: 10, color: INK, gap: 5 });

  // ---- message ----
  heading('Message');
  kv('Subject', rec.subject || '—');
  kv('From', rec.from_addr || '—');
  kv('Reply-To', rec.reply_to || '—');
  kv('Return-Path', rec.return_path || '—');
  kv('Message-ID', rec.message_id || '—', mono);
  kv('Date', rec.date ? new Date(rec.date).toUTCString() : '—');
  kv('Size', `${(rec.size_bytes / 1024).toFixed(1)} KB · ${rec.body_format}`);
  const dom = (a: string | null) => (a && a.includes('@') ? a.split('@').pop()!.toLowerCase() : null);
  const aligned = !(dom(rec.reply_to) && dom(rec.from_addr) && dom(rec.reply_to) !== dom(rec.from_addr));
  kv('Domain alignment', aligned ? 'From / Reply-To domains aligned' : 'NOT aligned (reply diverts to another domain)');

  // ---- scored evidence ----
  heading('Threat indicators (scored evidence)');
  if (!pos.length) text('No positive threat indicators — message assessed clean.', { color: MUTED });
  for (const c of pos) {
    need(26);
    page.drawText(`+${c.points.toFixed(0)}`, { x: MARGIN, y: y - 9, size: 10, font: bold, color: bandColor(v.band) });
    page.drawText(c.label, { x: MARGIN + 34, y: y - 9, size: 9.5, font: bold, color: INK });
    page.drawText(`[${c.analyzer}]`, { x: A4.w - MARGIN - 30, y: y - 9, size: 8, font, color: MUTED });
    y -= 13;
    if (c.rationale) text(c.rationale, { size: 8.5, color: MUTED, x: MARGIN + 34, gap: 3 });
    y -= 3;
  }
  if (v.suppressed_negatives?.length) {
    text(`Note: this message authenticated correctly (${v.suppressed_negatives.join(', ')}), but that credit was withheld because deception indicators were also present — a compromised or attacker-owned domain signs validly too.`,
      { size: 8.5, color: MED, gap: 3 });
  }

  // ---- authentication ----
  heading('Authentication (SPF / DKIM / DMARC)');
  const has = (sig: string) => rec.evidence.some((e) => e.signal === sig && e.status === 'TRIGGERED');
  const spf = has('spf_fail_hard') ? 'FAIL (hard)' : 'Pass / not enforced';
  const dkim = has('dkim_fail') ? 'FAIL (invalid signature)' : has('dkim_valid_aligned') ? 'PASS (valid & aligned)' : 'Not enforced (no signature)';
  const dmarc = has('dmarc_fail_strict') ? 'FAIL (strict policy violated)' : 'Pass / not enforced';
  kv('SPF', spf);
  kv('DKIM', dkim);
  kv('DMARC', dmarc);

  // ---- relay trace ----
  heading('Relay trace & trust boundary');
  const boundary = rec.hops.find((h) => h.trust === 'BOUNDARY');
  text(`Authenticated origin: ${boundary?.from_ip ?? 'none — no hop could be authenticated'}. The bottom-most hop is attacker-forgeable; we report the earliest hop we can authenticate and mark everything below it UNVERIFIED.`,
    { size: 8.5, color: MUTED, gap: 3 });
  y -= 2;
  need(16);
  page.drawText('SEQ', { x: MARGIN, y: y - 9, size: 8, font: bold, color: MUTED });
  page.drawText('FROM IP', { x: MARGIN + 34, y: y - 9, size: 8, font: bold, color: MUTED });
  page.drawText('BY HOST', { x: MARGIN + 150, y: y - 9, size: 8, font: bold, color: MUTED });
  page.drawText('TRUST', { x: A4.w - MARGIN - 70, y: y - 9, size: 8, font: bold, color: MUTED });
  y -= 14;
  for (const h of rec.hops) {
    need(13);
    const tc = h.trust === 'BOUNDARY' ? VIOLET : h.trust === 'TRUSTED' ? LOW : MED;
    page.drawText(`${h.seq}`, { x: MARGIN, y: y - 8, size: 8.5, font, color: INK });
    page.drawText(h.from_ip || '—', { x: MARGIN + 34, y: y - 8, size: 8.5, font: mono, color: INK });
    page.drawText((h.by_host || '—').slice(0, 34), { x: MARGIN + 150, y: y - 8, size: 8, font, color: INK });
    page.drawText(h.trust, { x: A4.w - MARGIN - 70, y: y - 8, size: 8, font: bold, color: tc });
    y -= 12;
  }

  // ---- IOCs ----
  const art = caseArtifacts(rec);
  heading('Indicators of compromise (IOCs)');
  const list = (label: string, items: string[]) => {
    if (!items.length) return;
    need(14);
    page.drawText(label, { x: MARGIN, y: y - 9, size: 9, font: bold, color: INK });
    y -= 13;
    for (const it of items) text(`- ${it}`, { size: 8.5, color: INK, x: MARGIN + 8, gap: 3, f: mono });
    y -= 2;
  };
  list('IP addresses', art.ips.map((i) => `${i.ip}  (hop ${i.hop}, ${i.trust})`));
  list('Domains', art.domains);
  list('URLs', art.urls.map((u) => `${u.url}${u.mismatched ? '  [anchor mismatch]' : u.shortened ? '  [shortener]' : ''}`));
  list('Sender addresses', art.emails);
  list('Attachments', art.attachments.map((a) => `${a.filename || 'unnamed'}  (${a.content_type || '?'}, ${((a.size_bytes || 0) / 1024).toFixed(1)} KB)  sha256:${(a.sha256 || '').slice(0, 24)}...`));
  if (!art.ips.length && !art.domains.length && !art.urls.length && !art.attachments.length) text('No IOCs extracted.', { color: MUTED });

  // ---- coverage ----
  heading('Analysis coverage');
  const lanes = [['M2', 'Header & relay'], ['M3', 'Authentication'], ['M4', 'Content (AI)'], ['M5', 'Network & geo'], ['M6', 'Domain'], ['M7', 'Correlation']];
  const unavail = new Set(v.lanes_unavailable);
  for (const [id, name] of lanes) {
    need(13);
    const ok = !unavail.has(id as never);
    page.drawText(ok ? '+' : '!', { x: MARGIN, y: y - 8, size: 9, font: bold, color: ok ? LOW : MED });
    page.drawText(`${id} — ${name}`, { x: MARGIN + 16, y: y - 8, size: 9, font, color: INK });
    page.drawText(ok ? 'ran' : 'unavailable (lowers confidence)', { x: MARGIN + 170, y: y - 8, size: 8.5, font, color: ok ? MUTED : MED });
    y -= 12;
  }

  footer();
  return doc.save();
}
